version: 2.1
orbs:
  elixir: membraneframework/elixir@1

workflows:
  build:
    jobs:
      - elixir/build_test:
          filters: &filters
            tags:
              only: /v.*/
          cache-version: 3
      - elixir/test:
          filters:
            <<: *filters
          cache-version: 2
      - elixir/lint:
          filters:
            <<: *filters
          cache-version: 2
      - elixir/hex_publish:
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
          context:
            - Deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
          cache-version: 2
